name: Deploy CDK via GitHub OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # 👈 Required for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: 🔍 Debug OIDC Context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Expected sub claim: repo:$GITHUB_REPOSITORY:ref:$GITHUB_REF"
          echo "Actual sub claim: $OIDC_CLAIM_sub"
          echo "Actual iss claim: $OIDC_CLAIM_iss"
          echo "Actual aud claim: $OIDC_CLAIM_aud"
          echo "Actual iat claim: $OIDC_CLAIM_iat"
          echo "Actual exp claim: $OIDC_CLAIM_exp"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::649455151029:role/githubASction
          role-session-name: github-actions-cdk
          aws-region: us-east-1

      - name: Build CDK
        run: npm run build

      - name: Bootstrap CDK (safe to run always)
        run: cdk bootstrap

      - name: Deploy all stacks
        run: cdk deploy --all --require-approval never
